using './main.bicep'

param namePrefix = 'canary'
param containerImage = 'ghcr.io/munishgoyal1/tripplanner:latest'
param azureOpenAiEndpoint = 'https://aoaicanarymd1ks-2703a.openai.azure.com/'
param azureOpenAiDeployment = 'gpt-4-1-canary'
param azureOpenAiApiVersion = '2024-10-21'
param azureOpenAiApiKey = readEnvironmentVariable('AZURE_OPENAI_API_KEY', '')
param duffelApiKey = readEnvironmentVariable('DUFFEL_API_KEY', '')
param liteapiApiKey = readEnvironmentVariable('LITEAPI_API_KEY', '')
param liteapiBaseUrl = readEnvironmentVariable('LITEAPI_BASE_URL', 'https://api.liteapi.travel/v3.0')
param travelHotelProvider = readEnvironmentVariable('TRAVEL_HOTEL_PROVIDER', 'auto')
param travelFlightProvider = readEnvironmentVariable('TRAVEL_FLIGHT_PROVIDER', 'auto')
param viatorApiKey = readEnvironmentVariable('VIATOR_API_KEY', '')
param viatorBaseUrl = readEnvironmentVariable('VIATOR_BASE_URL', 'https://api.sandbox.viator.com/partner')
param travelActivityProvider = readEnvironmentVariable('TRAVEL_ACTIVITY_PROVIDER', 'auto')
param openRouteServiceApiKey = readEnvironmentVariable('OPENROUTESERVICE_API_KEY', '')
param openRouteServiceBaseUrl = readEnvironmentVariable('OPENROUTESERVICE_BASE_URL', 'https://api.openrouteservice.org')
param openRouteServiceRouteTtlSec = int(readEnvironmentVariable('OPENROUTESERVICE_ROUTE_TTL_SEC', '21600'))
param cacheRedisEnabled = readEnvironmentVariable('CACHE_REDIS_ENABLED', '0') == '1'
param cacheRedisUrl = readEnvironmentVariable('CACHE_REDIS_URL', '')
param cacheRedisNamespace = readEnvironmentVariable('CACHE_REDIS_NAMESPACE', 'tripplanner:provider-cache')
param cacheRedisConnectTimeoutSec = readEnvironmentVariable('CACHE_REDIS_CONNECT_TIMEOUT_SEC', '0.2')
param cacheRedisSocketTimeoutSec = readEnvironmentVariable('CACHE_REDIS_SOCKET_TIMEOUT_SEC', '0.2')
param enableGooglePlaces = false
param googlePlacesApiKey = readEnvironmentVariable('GOOGLE_PLACES_API_KEY', '')
param googleMapsBrowserKey = readEnvironmentVariable('GOOGLE_MAPS_BROWSER_KEY', '')
param tavilyApiKey = readEnvironmentVariable('TAVILY_API_KEY', '')
param googleOauthClientId = readEnvironmentVariable('OAUTH_GOOGLE_CLIENT_ID', '')
param googleOauthClientSecret = readEnvironmentVariable('OAUTH_GOOGLE_CLIENT_SECRET', '')
param githubOauthClientId = readEnvironmentVariable('OAUTH_GITHUB_CLIENT_ID', '')
param githubOauthClientSecret = readEnvironmentVariable('OAUTH_GITHUB_CLIENT_SECRET', '')
param webSessionSecret = readEnvironmentVariable('WEB_SESSION_SECRET', readEnvironmentVariable('CHAINLIT_AUTH_SECRET', ''))
param oauthRedirectBase = ''
param cosmosAccountName = readEnvironmentVariable('COSMOS_ACCOUNT_NAME', '')
param cosmosResourceGroupName = readEnvironmentVariable('COSMOS_RESOURCE_GROUP', 'rg-tripplanner-data')
param cosmosDatabaseName = 'tripplanner-canary'
param minReplicas = 0
param maxReplicas = 1
