import type {
  Itinerary,
  ItineraryDay,
  ItineraryStop,
  TripOverview,
  TripVerification,
  UnmappedStop,
} from "../../../src/types";

/**
 * One Rajasthan trip, typed against the production client contracts, so the
 * "Today" preview can hand it to the real ItineraryPanel and every option is
 * judged on exactly the facts production would receive.
 *
 * It deliberately exercises every branch the pane renders: a flight and an
 * arrival airport, a hotel circuit with a return row, a transition day that
 * checks out of one hotel and into another, an inter-city road leg, estimated
 * times, a buffer and a timing conflict, a concern, notes and insights, a stop
 * the map could not pin, and rain likely enough to be called out.
 */

const DAY_COLORS = ["#c2410c", "#0f766e", "#7c3aed", "#2563eb"];

function stop(day: number, fields: Partial<ItineraryStop> & Pick<ItineraryStop, "name" | "kind" | "time">): ItineraryStop {
  return {
    duration_min: null,
    note: "",
    booked: false,
    selected: true,
    color: DAY_COLORS[day - 1],
    ...fields,
  };
}

function travel(mode: string, km: number, minutes: number, detail?: string) {
  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;
  return {
    mode,
    distance_km: km,
    duration_min: minutes,
    distance_display: `${km.toLocaleString("en", { maximumFractionDigits: 1 })} km`,
    duration_display: hours ? `${hours} hr${hours > 1 ? "s" : ""}${rest ? ` ${rest} min` : ""}` : `${minutes} min`,
    ...(detail ? { detail } : {}),
  };
}

const day1: ItineraryDay = {
  day: 1,
  date: "2026-10-14",
  title: "Arrival and the Pink City",
  color: DAY_COLORS[0],
  summary:
    "Land by breakfast, settle into the hotel, then walk the Pink City's two great landmarks before a classic Rajasthani thali. The afternoon stays open for rest before sunset from Nahargarh's ramparts.",
  reachability: "Old-city stops are a short walk apart; the fort needs a cab both ways.",
  google_maps_url: "https://www.google.com/maps/dir/Jaipur+Airport/ITC+Rajputana/Hawa+Mahal/Jantar+Mantar/Nahargarh+Fort",
  route: travel("Drive", 39.9, 149),
  schedule: {
    start: "06:10",
    end: "19:15",
    duration_min: 785,
    duration_display: "13 hrs 5 min",
    travel_duration_min: 149,
    travel_duration_display: "2 hrs 29 min",
    estimated: false,
  },
  weather: { date: "2026-10-14", summary: "Sunny", condition: "clear", high_c: 33, low_c: 21, precip_mm: 0, precip_probability_pct: 5 },
  stops: [
    stop(1, {
      name: "Flight: Bengaluru (BLR) to Jaipur (JAI)",
      kind: "flight",
      time: "06:10",
      duration_min: 150,
      departure_time: "08:40",
      booked: true,
      cost_display: "₹9,840",
      note: "IndiGo 6E 512 · web check-in opens 48 hours before departure",
    }),
    stop(1, {
      name: "Jaipur International Airport",
      kind: "airport",
      time: "08:40",
      terminal_role: "arrival",
      note: "Meet the pre-booked driver outside Gate 2",
    }),
    stop(1, {
      name: "ITC Rajputana",
      kind: "hotel",
      time: "09:45",
      booked: true,
      cost_display: "₹14,500 per night",
      rating: 4.5,
      review_count: 18200,
      note: "Early check-in requested; confirm by email the day before",
      travel_from_previous: travel("Drive", 12, 30, "Airport pre-paid taxi via Tonk Road"),
      expected_arrival_time: "09:10",
      buffer_before_min: 35,
      buffer_before_display: "35 min",
    }),
    stop(1, {
      name: "Hawa Mahal",
      kind: "attraction",
      time: "11:30",
      duration_min: 60,
      departure_time: "12:30",
      opening_hours: "09:00–16:30",
      cost_display: "₹200",
      rating: 4.4,
      review_count: 112000,
      popularity_score: 92,
      insight: "Arrive before noon: the façade is best lit from the rooftop café across the street.",
      note: "Photography is allowed inside; tripods are not.",
      travel_from_previous: travel("Drive", 5.8, 22, "Via MI Road; old-city lanes slow down after 11:00"),
      expected_arrival_time: "10:40",
      buffer_before_min: 50,
      buffer_before_display: "50 min",
    }),
    stop(1, {
      name: "Jantar Mantar",
      kind: "attraction",
      time: "12:45",
      duration_min: 75,
      departure_time: "14:00",
      opening_hours: "09:00–16:30",
      cost_display: "₹200",
      rating: 4.5,
      review_count: 64000,
      popularity_score: 88,
      booked: true,
      insight: "The 12:45 guided slot explains the Samrat Yantra sundial; it fills quickly.",
      travel_from_previous: travel("Walk", 0.6, 8, "Through Tripolia Bazaar"),
      expected_arrival_time: "12:38",
      buffer_before_min: 7,
      buffer_before_display: "7 min",
    }),
    stop(1, {
      name: "Lunch at Laxmi Mishthan Bhandar",
      kind: "meal",
      time: "14:15",
      duration_min: 60,
      departure_time: "15:15",
      cost_display: "₹1,200 for two",
      rating: 4.1,
      review_count: 21000,
      note: "Vegetarian thali; ask for the ghewar to finish.",
      travel_from_previous: travel("Walk", 1.1, 14),
      expected_arrival_time: "14:14",
      buffer_before_min: 1,
      buffer_before_display: "1 min",
    }),
    stop(1, {
      name: "Nahargarh Fort sunset",
      kind: "attraction",
      time: "17:00",
      duration_min: 90,
      departure_time: "18:30",
      time_estimated: true,
      opening_hours: "10:00–22:00",
      cost_display: "₹200",
      rating: 4.4,
      review_count: 57000,
      popularity_score: 81,
      concern: "The last 2 km is a steep single-lane road; allow extra time after 16:30.",
      travel_from_previous: travel("Drive", 9.4, 35, "Via the Nahargarh Road hairpins"),
      expected_arrival_time: "15:50",
      buffer_before_min: 70,
      buffer_before_display: "1 hr 10 min",
    }),
    stop(1, {
      name: "ITC Rajputana",
      kind: "hotel",
      time: "19:15",
      booked: true,
      cost_display: "₹14,500 per night",
      rating: 4.5,
      review_count: 18200,
      note: "Return to your stay",
      travel_from_previous: travel("Drive", 11, 40),
      expected_arrival_time: "19:10",
      buffer_before_min: 5,
      buffer_before_display: "5 min",
    }),
  ],
};

const day2: ItineraryDay = {
  day: 2,
  date: "2026-10-15",
  title: "Amber Fort and the palace circuit",
  color: DAY_COLORS[1],
  summary:
    "An early start beats the crowds up to Amber Fort, with the stepwell and the lake palace on the way back into town. Lunch sits between the two palaces, and the evening ends at a village-style dinner south of the city.",
  reachability: "Amer is 11 km north of the hotel; everything after lunch is inside the old city.",
  google_maps_url: "https://www.google.com/maps/dir/ITC+Rajputana/Amber+Fort/Panna+Meena+ka+Kund/Jal+Mahal/City+Palace+Jaipur",
  route: travel("Drive", 58.2, 176),
  schedule: {
    start: "07:45",
    end: "21:30",
    duration_min: 825,
    duration_display: "13 hrs 45 min",
    travel_duration_min: 176,
    travel_duration_display: "2 hrs 56 min",
    estimated: true,
  },
  weather: { date: "2026-10-15", summary: "Partly cloudy", condition: "partly_cloudy", high_c: 32, low_c: 22, precip_mm: 0.2, precip_probability_pct: 20 },
  stops: [
    stop(2, { name: "ITC Rajputana", kind: "hotel", time: "07:45", booked: true, cost_display: "₹14,500 per night", rating: 4.5, review_count: 18200, note: "Start from your stay" }),
    stop(2, {
      name: "Amber Fort",
      kind: "attraction",
      time: "08:30",
      duration_min: 150,
      departure_time: "11:00",
      opening_hours: "08:00–17:30",
      cost_display: "₹500",
      rating: 4.6,
      review_count: 98000,
      popularity_score: 95,
      booked: true,
      insight: "Take the jeep up from Amer village; the elephant rides are not recommended.",
      note: "Hire an official guide at the Suraj Pol ticket window (about ₹400).",
      travel_from_previous: travel("Drive", 11.2, 35, "Leave before 08:00 to clear Amer Road traffic"),
      expected_arrival_time: "08:20",
      buffer_before_min: 10,
      buffer_before_display: "10 min",
    }),
    stop(2, {
      name: "Panna Meena ka Kund",
      kind: "attraction",
      time: "11:15",
      duration_min: 30,
      departure_time: "11:45",
      cost_display: "Free",
      rating: 4.5,
      review_count: 24000,
      popularity_score: 74,
      insight: "The criss-cross stairs photograph best from the north-east corner.",
      travel_from_previous: travel("Walk", 0.9, 12),
      expected_arrival_time: "11:12",
      buffer_before_min: 3,
      buffer_before_display: "3 min",
    }),
    stop(2, {
      name: "Jal Mahal viewpoint",
      kind: "attraction",
      time: "12:10",
      duration_min: 20,
      departure_time: "12:30",
      duration_estimated: true,
      cost_display: "Free",
      rating: 4.3,
      review_count: 41000,
      popularity_score: 78,
      note: "Viewpoint only; the palace itself is closed to visitors.",
      travel_from_previous: travel("Drive", 6.5, 18),
      expected_arrival_time: "12:03",
      buffer_before_min: 7,
      buffer_before_display: "7 min",
    }),
    stop(2, {
      name: "Lunch at 1135 AD",
      kind: "meal",
      time: "13:00",
      duration_min: 75,
      departure_time: "14:15",
      cost_display: "₹4,500 for two",
      rating: 4.3,
      review_count: 6200,
      concern: "Reservation not yet confirmed; weekday lunch usually has tables.",
      travel_from_previous: travel("Drive", 8.1, 40, "Back up to Amer; the fort car park is busy at lunchtime"),
      expected_arrival_time: "13:10",
      timing_conflict_min: 10,
      timing_conflict_display: "10 min",
    }),
    stop(2, {
      name: "City Palace Jaipur",
      kind: "attraction",
      time: "15:00",
      duration_min: 120,
      departure_time: "17:00",
      opening_hours: "09:30–17:00",
      cost_display: "₹700",
      rating: 4.4,
      review_count: 71000,
      popularity_score: 90,
      insight: "The Pritam Niwas Chowk peacock gates are in the inner courtyard; do not skip it.",
      travel_from_previous: travel("Drive", 10.4, 32),
      expected_arrival_time: "14:47",
      buffer_before_min: 13,
      buffer_before_display: "13 min",
    }),
    stop(2, {
      name: "Johari Bazaar textile lanes",
      kind: "attraction",
      time: "17:15",
      duration_min: 60,
      departure_time: "18:15",
      cost_display: "Free",
      rating: 4.2,
      review_count: 9100,
      popularity_score: 63,
      note: "Block-printed cotton is best bought by the metre on the side lanes.",
      travel_from_previous: travel("Walk", 0.8, 11),
      expected_arrival_time: "17:11",
      buffer_before_min: 4,
      buffer_before_display: "4 min",
    }),
    stop(2, {
      name: "Dinner at Chokhi Dhani",
      kind: "meal",
      time: "19:00",
      duration_min: 120,
      departure_time: "21:00",
      cost_display: "₹2,400 for two",
      rating: 4.2,
      review_count: 88000,
      insight: "Folk dance and puppet shows run all evening; the dinner seating is at 19:30.",
      travel_from_previous: travel("Drive", 20.3, 45, "South on Tonk Road"),
      expected_arrival_time: "19:00",
      buffer_before_min: 0,
      buffer_before_display: "0 min",
    }),
    stop(2, {
      name: "ITC Rajputana",
      kind: "hotel",
      time: "21:30",
      booked: true,
      cost_display: "₹14,500 per night",
      rating: 4.5,
      review_count: 18200,
      note: "Return to your stay",
      travel_from_previous: travel("Drive", 21.1, 30),
      expected_arrival_time: "21:30",
    }),
  ],
};

const day3: ItineraryDay = {
  day: 3,
  date: "2026-10-16",
  title: "Jaipur to Udaipur via Chittorgarh",
  color: DAY_COLORS[2],
  summary:
    "A scenic road day south through the Aravalli foothills, breaking the drive at Chittorgarh, India's largest fort. You reach Udaipur in time for the boat across to the Lake Palace.",
  reachability: "Long road day: two drives totalling about 7 hours 20 minutes, broken by the fort and lunch.",
  google_maps_url: "https://www.google.com/maps/dir/ITC+Rajputana/Chittorgarh+Fort/Taj+Lake+Palace",
  route: travel("Drive", 418, 470),
  schedule: {
    start: "07:30",
    end: "18:30",
    duration_min: 660,
    duration_display: "11 hrs",
    travel_duration_min: 470,
    travel_duration_display: "7 hrs 50 min",
    estimated: true,
  },
  weather: { date: "2026-10-16", summary: "Chance of showers", condition: "rain", high_c: 29, low_c: 20, precip_mm: 3.4, precip_probability_pct: 55 },
  stops: [
    stop(3, { name: "ITC Rajputana", kind: "hotel", time: "07:30", booked: true, cost_display: "₹14,500 per night", rating: 4.5, review_count: 18200 }),
    stop(3, {
      name: "Drive: Jaipur to Chittorgarh",
      kind: "transport",
      time: "07:45",
      duration_min: 300,
      departure_time: "12:45",
      duration_estimated: true,
      route_circuit_id: "road-3",
      cost_display: "₹11,000 private car, both legs",
      booked: true,
      note: "Your driver stays with you through to Udaipur.",
    }),
    stop(3, {
      name: "Chittorgarh Fort",
      kind: "attraction",
      time: "13:05",
      duration_min: 120,
      departure_time: "15:05",
      opening_hours: "09:30–17:00",
      cost_display: "₹600",
      rating: 4.5,
      review_count: 35000,
      popularity_score: 86,
      route_circuit_id: "road-3",
      insight: "Vijay Stambh and Padmini's palace are the two stops worth the walk in the heat.",
      travel_from_previous: travel("Drive", 6, 20, "Up the fort ramp road through seven gates"),
      expected_arrival_time: "13:05",
      buffer_before_min: 0,
      buffer_before_display: "0 min",
    }),
    stop(3, {
      name: "Drive: Chittorgarh to Udaipur",
      kind: "transport",
      time: "15:15",
      duration_min: 150,
      departure_time: "17:45",
      operational_time_display: "2 hrs 30 min transfer est.",
      route_circuit_id: "road-3",
      booked: true,
      note: "Rain is likely after 16:00 on the NH48 ghat section.",
    }),
    stop(3, {
      name: "Taj Lake Palace",
      kind: "hotel",
      time: "18:15",
      cost_display: "₹42,000 per night",
      rating: 4.8,
      review_count: 9800,
      concern: "Boat transfer runs from Bansi Ghat only; the last jetty departure is 23:00.",
      note: "Room not yet confirmed; the lake-view category has two rooms left.",
      travel_from_previous: travel("Boat", 0.4, 10, "Hotel launch from Bansi Ghat"),
      expected_arrival_time: "18:05",
      buffer_before_min: 10,
      buffer_before_display: "10 min",
    }),
  ],
};

const day4: ItineraryDay = {
  day: 4,
  date: "2026-10-17",
  title: "Lake Pichola and home",
  color: DAY_COLORS[3],
  summary:
    "A slow final morning on the lake: the City Palace museum, a haveli courtyard, and lunch on the Ambrai ghat before the afternoon flight home.",
  reachability: "The palace and haveli are a 10-minute walk apart; allow 40 minutes to the airport.",
  google_maps_url: "https://www.google.com/maps/dir/Taj+Lake+Palace/City+Palace+Udaipur/Bagore+ki+Haveli/Ambrai/Udaipur+Airport",
  route: travel("Drive", 29.6, 71),
  schedule: {
    start: "09:00",
    end: "18:45",
    duration_min: 585,
    duration_display: "9 hrs 45 min",
    travel_duration_min: 71,
    travel_duration_display: "1 hr 11 min",
    estimated: false,
  },
  weather: { date: "2026-10-17", summary: "Clear", condition: "clear", high_c: 30, low_c: 19, precip_mm: 0, precip_probability_pct: 10 },
  stops: [
    stop(4, { name: "Taj Lake Palace", kind: "hotel", time: "09:00", cost_display: "₹42,000 per night", rating: 4.8, review_count: 9800 }),
    stop(4, {
      name: "City Palace Udaipur",
      kind: "attraction",
      time: "09:30",
      duration_min: 120,
      departure_time: "11:30",
      opening_hours: "09:00–21:00",
      cost_display: "₹400",
      rating: 4.6,
      review_count: 52000,
      popularity_score: 91,
      insight: "The Mor Chowk peacock mosaics are at the far end of the museum route.",
      travel_from_previous: travel("Boat", 0.6, 15, "Hotel launch to the City Palace jetty"),
      expected_arrival_time: "09:15",
      buffer_before_min: 15,
      buffer_before_display: "15 min",
    }),
    stop(4, {
      name: "Bagore ki Haveli",
      kind: "attraction",
      time: "11:45",
      duration_min: 45,
      departure_time: "12:30",
      opening_hours: "10:00–17:30",
      cost_display: "₹100",
      rating: 4.4,
      review_count: 14000,
      popularity_score: 70,
      travel_from_previous: travel("Walk", 0.7, 10, "Along Gangaur Ghat"),
      expected_arrival_time: "11:40",
      buffer_before_min: 5,
      buffer_before_display: "5 min",
    }),
    stop(4, {
      name: "Lunch at Ambrai",
      kind: "meal",
      time: "12:45",
      duration_min: 75,
      departure_time: "14:00",
      cost_display: "₹3,800 for two",
      rating: 4.4,
      review_count: 11000,
      booked: true,
      insight: "Ask for a ghat-side table; the view back across to the palace is the best in town.",
      travel_from_previous: travel("Drive", 2.4, 12),
      expected_arrival_time: "12:42",
      buffer_before_min: 3,
      buffer_before_display: "3 min",
    }),
    stop(4, {
      name: "Maharana Pratap Airport",
      kind: "airport",
      time: "14:45",
      terminal_role: "departure",
      note: "Security queues are short; 80 minutes before departure is enough.",
      travel_from_previous: travel("Drive", 24, 40),
      expected_arrival_time: "14:40",
      buffer_before_min: 5,
      buffer_before_display: "5 min",
    }),
    stop(4, {
      name: "Flight: Udaipur (UDR) to Bengaluru (BLR)",
      kind: "flight",
      time: "16:05",
      duration_min: 160,
      departure_time: "18:45",
      booked: true,
      cost_display: "₹11,260",
      note: "IndiGo 6E 745 · 15 kg checked bag each",
    }),
  ],
};

const days = [day1, day2, day3, day4];
const plannedStops = days.flatMap((day) => day.stops.filter((entry) => !["hotel", "airport", "origin"].includes(entry.kind)));

export const itinerary: Itinerary = {
  has_itinerary: true,
  destination: "Jaipur & Udaipur",
  currency: "INR",
  days,
  stats: {
    days: days.length,
    stops: plannedStops.length,
    booked: plannedStops.filter((entry) => entry.booked).length,
  },
};

export const unmappedStops: UnmappedStop[] = [
  {
    name: "Johari Bazaar textile lanes",
    kind: "attraction",
    day: 2,
    tier: "place",
    reason: "no_match",
    candidate: { name: "Johari Bazar", place_id: "lab-johari", lat: 26.922, lng: 75.826 },
  },
];

export const overview: TripOverview = {
  destination: "Jaipur & Udaipur",
  origin: "Bengaluru",
  departure_date: "2026-10-14",
  return_date: "2026-10-17",
  travelers: 2,
  status: "planning",
  notes:
    "A four-day Rajasthan loop for two: the Pink City's forts and bazaars, a scenic road day via Chittorgarh, and a final morning on Lake Pichola.",
  counts: { flights: 2, hotels: 2, activities: 13, days: 4 },
  total_cost: 184300,
  total_cost_display: "₹1,84,300",
  cost_evidence: {
    currency: "INR",
    lines: [],
    priced_total: 184300,
    priced_count: 9,
    stale_count: 2,
    unverified_count: 3,
    unpriced_count: 0,
    complete: false,
    coverage_pct: 64,
    summary: "9 of 14 prices from live quotes",
  },
  price_rechecks: [
    { kind: "hotel", provider: "Booking.com", reason: "Quote older than 24 hours" },
    { kind: "flight", provider: "IndiGo", reason: "Fare may have changed" },
  ],
  budget: {
    currency: "INR",
    spent: 184300,
    spent_display: "₹1,84,300",
    travelers: 2,
    per_traveler: 92150,
    per_traveler_display: "₹92,150",
    breakdown: { flights: 21100, hotels: 113000, activities: 50200 },
    target: 220000,
    target_display: "₹2,20,000",
    remaining: 35700,
    remaining_display: "₹35,700",
    pct_used: 84,
    over_budget: false,
    estimated: true,
    evidence_coverage_pct: 64,
    verified_spent: 118400,
    all_in_spent: 118400,
    all_in_coverage_pct: 72,
    required_unknown: ["Chittorgarh guide fee", "Lake Palace boat transfer"],
  },
  weather: {
    source: "forecast",
    source_label: "Forecast · Open-Meteo",
    note: "",
    days: days.map((day) => day.weather!),
    packing_advice: [
      "Light cotton layers for 33°C afternoons",
      "A compact umbrella for Friday's showers",
      "A scarf or shawl for temple visits",
    ],
  },
  family_pills: ["2 adults", "Vegetarian", "Moderate pace"],
  constraints: ["No elephant rides", "Back at the hotel by 21:30", "Budget ₹2,20,000 all-in"],
};

export const verification: TripVerification = {
  verdict: "partial",
  counts: { total: 9, passed: 6, failed: 1, unverified: 2 },
  checks: [
    { code: "hours", rule: "Opening hours", statement: "Every timed visit falls inside the place's published hours.", status: "passed", severity: "contradiction", findings: [], gaps: [] },
    { code: "sequence", rule: "Travel time", statement: "Each stop is reachable from the previous one before its start time.", status: "failed", severity: "advisory", findings: ["Day 2: Lunch at 1135 AD starts 10 min before you can arrive."], gaps: [] },
    { code: "flights", rule: "Flights", statement: "Arrival and departure flights bracket the trip dates.", status: "passed", severity: "contradiction", findings: [], gaps: [] },
    { code: "hotels", rule: "Hotel nights", statement: "Every night of the trip has a place to stay.", status: "passed", severity: "contradiction", findings: [], gaps: [] },
    { code: "meals", rule: "Meals", statement: "Every full day includes at least one meal stop.", status: "passed", severity: "advisory", findings: [], gaps: [] },
    { code: "closures", rule: "Closures", statement: "No planned place is marked permanently closed.", status: "unverified", severity: "contradiction", findings: [], gaps: [{ name: "Johari Bazaar textile lanes", day: 2, missing: ["place match"] }] },
  ],
  days: [
    { day: 1, status: "passed", findings: [], advisories: [], unverified: [], holiday: "" },
    { day: 2, status: "failed", findings: [], advisories: ["Lunch at 1135 AD starts 10 min before you can arrive."], unverified: ["Johari Bazaar textile lanes"], holiday: "" },
    { day: 3, status: "passed", findings: [], advisories: [], unverified: [], holiday: "" },
    { day: 4, status: "unverified", findings: [], advisories: [], unverified: ["Bagore ki Haveli"], holiday: "Maharishi Valmiki Jayanti" },
  ],
  unverified_stops: [
    { name: "Johari Bazaar textile lanes", day: 2, missing: ["opening hours", "place match"] },
    { name: "Bagore ki Haveli", day: 4, missing: ["holiday hours"] },
  ],
  freshness: { checked_at: "2026-09-13T18:20:00Z", checked: 14, total: 14, comparison_available: true, changes: [], failed: [] },
};

export const verificationHeadline: Record<TripVerification["verdict"], string> = {
  clear: "Everything we can check, checks out",
  partial: "Checked, with gaps we could not confirm",
  advisories: "Checked — a couple of days look tight",
  issues: "This plan contradicts itself",
  unverified: "Nothing to check yet",
};
